name: Merge Bot

on: pull_request

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: PR Merge Bot
      uses: squalrus/merge-bot@v0.4.1
      if: github.actor == 'imgbot[bot]'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        method: squash
